Fix `which` output escaping

diff --git a/usr/local/bin/vid2gif b/usr/local/bin/vid2gif
--- a/usr/local/bin/vid2gif
+++ b/usr/local/bin/vid2gif
@@ -26,7 +26,7 @@ fi
 find_program() {
     echo "$#"
     echo "$@"
-    which "${1}" 2>&1 > /dev/null || (echo "Failed to find ${1}. Please install it on your system." && exit 1)
+    (which "${1}" 2>&1) > /dev/null || (echo "Failed to find ${1}. Please install it on your system." && exit 1)
 }
 
 find_program gifski
